# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-09 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
