# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_auto_20160609_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned',
            field=models.IntegerField(default=0),
        ),
    ]
