# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_complaint_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
