# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0016_auto_20160829_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
