# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0017_auto_20160928_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
