# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0018_auto_20161024_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
