# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='changed_status',
            field=models.CharField(default='Submitted', max_length=120),
        ),
    ]
