# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-27 05:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0009_auto_20160622_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management',
            old_name='rating',
            new_name='priority',
        ),
        migrations.AddField(
            model_name='log',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_log', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
