# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20160627_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
