# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20160701_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='log',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
