# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0011_remove_complaint_assigned'),
        ('management', '0012_auto_20160702_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementuser',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='complaint.Category'),
            preserve_default=False,
        ),
    ]
